{% set version = "0.1.5" %}

package:
  name: pyosp
  version: {{ version }}

source:
  fn: pyosp-{{ version }}.tar.gz
  url: https://github.com/PyOSP-devs/PyOSP/archive/v{{ version }}.tar.gz
  sha256: e0244aa7cdd251f5cf79e9a66d6fcf9c01f759e0cb95241895482f65bc1a5afa 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - numpy

  run:
    - python >=3.6
    - numpy
    - matplotlib
    - gdal >3*
    - shapely
    - scipy
    - pytest

test:
  imports:
    - pyosp

about:
  home: https://github.com/PyOSP-devs/PyOSP
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python Object-oriented Swath Profile'
  doc_url: https://pyosp.readthedocs.io/en/latest/
  dev_url: https://github.com/PyOSP-devs/PyOSP

extra:
  recipe-maintainers:
    - yzh211
